spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'
      envers:
        audit_strategy: org.hibernate.envers.strategy.internal.ValidityAuditStrategy
        do_not_audit_optimistic_locking_field: false
    properties:
      hibernate:
        format-sql: true
        globally_quoted_identifiers: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE